uiConsts = {
    "ApplicationMinWidth": 800,
    "ApplicationMinHeight": 600,
    "ToolbarPadding": 8,
    "ToolbarTitlePadding": 8,
    "ToolbarTitleFontSize": 18,
    "ArtLayoutMargins": 32,
    "DrawerWidthCoefficient": 0.32,
    "DrawerTitleFontSize": 18,
    "DividerHeight": 1,
    "SettingsDialogWidthCoefficient": 0.5,
    "SettingsDialogItemSpacing": 16,
    "SettingsDialogHelpImageSize": 16,
    "TooltipDelay": 100,
    "ArtListItemHeight": 72,
    "ArtListItemImageWidth": 100,
    "ArtListItemImageHeight": 56,
    "ArtListItemTextPadding": 16,
    "ArtListItemTextFontSize": 16,
    "ArtListItemIconPadding": 8,

    "ToolbarTitle": "ASCII art",
    "DrawerTitle": "Image list",
    "PlayButtonText": "Play animation",
    "StopButtonText": "Stop animation",
    "SettingsButtonText": "Settings",
    "AddImgButtonTooltip": "Add image",
    "SettingsDialogTitle": "Settings",
    "SettingsDialogSaveButtonText": "Apply",
    "SettingsDialogCancelButtonText": "Cancel",
    "SettingsThemeTitle": "Theme",
    "SettingsThemeModels": ["Light", "Dark"],
    "SettingsGSLevelTitle": "Grayscale level",
    "SettingsGSLevelTooltip": "Enter sequence of symbols from darkest to lightest. "
                              "Your ASCII art will be shown by these symbols. "
                              "(Leave the field empty to use the default grayscale level)",

    "DrawerButtonImgSrc": "../drawable/menu.svg",
    "PlayButtonImgSrc": "../drawable/play.svg",
    "StopButtonImgSrc": "../drawable/pause.svg",
    "MoreButtonImgSrc": "../drawable/more.svg",
    "AddImgButtonImgSrc": "../drawable/add_image.svg",
    "SettingsIconHelpSrc": "../drawable/help.svg",
    "ArtListInfoImgSrc": "../drawable/more.svg",

    "DividerColor": "#1E000000",
    "ShadowColor": "#80212121"
}
