uiConsts = {
    "ApplicationMinWidth": 800,
    "ApplicationMinHeight": 600,
    "ToolbarPadding": 8,
    "ToolbarTitlePadding": 8,
    "ToolbarTitleFontSize": 18,
    "ArtLayoutMargins": 32,
    "DrawerWidthCoefficient": 0.25,
    "DrawerTitleFontSize": 18,
    "DialogWidthCoefficient": 0.44,
    "AddImageDialogWidthCoefficient": 0.55,
    "DialogItemSpacingVert": 32,
    "DialogItemSpacingHoriz": 16,
    "DialogHelpImageSize": 16,
    "TooltipDelay": 100,
    "ArtListItemHeight": 180,
    "ArtListItemElevation": 3,
    "ArtListItemFontSize": 16,
    "ArtListItemImageHeight": 135,
    "ArtListItemMargin": 18,
    "ArtListItemAnimationDuration": 150,
    "AddImageDialogPathBoxLeftMargin": 2,
    "AddImageDialogPathBoxRightMargin": 8,

    "ToolbarTitle": "ASCII art",
    "DrawerTitle": "Image list",
    "PlayButtonText": "Play animation",
    "StopButtonText": "Stop animation",
    "SettingsButtonText": "Settings",
    "AddImgButtonText": "Add image",
    "AddImgEffectsText": "Image effects",
    "AddImgContrastEffectText": "Contrast",
    "AddImgNegativeEffectText": "Negative",
    "AddImgConvolutionEffectText": "Convolution",
    "ArtListItemPropertiesBtn": "Properties",
    "ArtListItemRemoveBtn": "Remove image",
    "AddImageDialogNameTitle": "Art name",
    "AddImageDialogImgPathTitle": "Path to image...",
    "AddImageDialogBrowseBtn": "Browse",
    "AddImageDialogAddBtn": "Add",
    "AddImageDialogSaveBtn": "Save",
    "SettingsDialogSaveButtonText": "Apply",
    "DialogCancelButtonText": "Cancel",
    "SettingsThemeTitle": "Theme",
    "SettingsThemeModels": ["Light", "Dark"],
    "SettingsGSLevelTitle": "Grayscale level",
    "SettingsGSLevelTooltip": "Enter sequence of symbols from darkest to lightest. "
                              "Your ASCII art will be shown by these symbols. "
                              "(Leave the field empty to use the default grayscale level)",
    "AddImageDialogRequiredTootlip": "Required field",

    "DrawerButtonImgSrc": "../../drawable/menu.svg",
    "PlayButtonImgSrc": "../../drawable/play.svg",
    "StopButtonImgSrc": "../../drawable/pause.svg",
    "MoreButtonImgSrc": "../../drawable/more.svg",
    "AddImgButtonImgSrc": "../../drawable/add_image.svg",
    "SettingsIconHelpSrc": "../../drawable/help.svg",
    "AddImageIconRequiredSrc": "../../drawable/warning.svg",
    "ArtListInfoImgSrc": "../../drawable/more.svg",

    "ShadowColor": "#80212121"
}
